// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package authors

import (
	"database/sql"
)

type User struct {
	ID        int64
	Name      string
	Email     string
	Lastlogin sql.NullTime
	Updateat  sql.NullTime
	Createdat sql.NullTime
}
