// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: UserService.sql

package authors

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO User (name, email)
VALUES (?, ?)
`

type CreateUserParams struct {
	Name  string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser, arg.Name, arg.Email)
}

const findAll = `-- name: FindAll :many
SELECT id, name, email, lastlogin, updateat, createdat FROM User
ORDER BY name
`

func (q *Queries) FindAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Lastlogin,
			&i.Updateat,
			&i.Createdat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, lastlogin, updateat, createdat FROM User
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Lastlogin,
		&i.Updateat,
		&i.Createdat,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, lastlogin, updateat, createdat FROM User
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Lastlogin,
		&i.Updateat,
		&i.Createdat,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
SELECT id, name, email, lastlogin, updateat, createdat FROM User
WHERE email = ? and name = ? LIMIT 1
`

type VerifyUserParams struct {
	Email string
	Name  string
}

func (q *Queries) VerifyUser(ctx context.Context, arg VerifyUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, verifyUser, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Lastlogin,
		&i.Updateat,
		&i.Createdat,
	)
	return i, err
}
