CREATE TABLE User (
  id   BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name  text   NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE,
  lastLogin DATETIME,
  UpdateAt  DATETIME   DEFAULT CURRENT_TIMESTAMP,
  CreatedAt DATETIME  DEFAULT CURRENT_TIMESTAMP
);